### ISSUE TITLE
How is the screenshot effect in the example implemented?

### ISSUE THREAD

**Issue by HonghaiHuang** [KestrelRadarSensors/dockingpanes#13]
Hello, I see a screenshot of the example on the home page. How can this code be implemented?
![gith](https://user-images.githubusercontent.com/19658442/88027516-f4f62c80-cb69-11ea-83c9-b80f727036a0.png)

**Comment by KestrelAdrian** [comment]
It's a subclassed QTabBar that draws the tab header and items itself.
