### ISSUE TITLE
Linux Shadow Issue

### ISSUE THREAD

**Issue by KestrelAdrian** [KestrelRadarSensors/dockingpanes#9]
Report from user on Facebook, the shadow (DockingPaneGlowWidget) does not draw (or move) correctly under Ubuntu.

@lmsoria Have you seen this issue as you're a linux user?

![105702677_2699581673646731_5550232594675133879_n](https://user-images.githubusercontent.com/1521090/86522186-1957c680-be52-11ea-9d6a-31cd1972610b.jpg)

**Comment by lmsoria** [comment]
Several things to report: 
To compile the project on Ubuntu I had to edit those lines on `simple.pro`:
```
CONFIG(debug, debug|release) {
    LIBS += -L$$OUT_PWD/../../src/ -lDockingPanes
} else {
    LIBS += -L$$OUT_PWD/../../src/release/ -lDockingPanes
}
```

On another hand, I can confirm that the behavior is really strange, compare to Windows version (on which I made the last commits that I pushed recently). Here a gif:
![output](https://user-images.githubusercontent.com/17966040/86523758-86b22a00-be47-11ea-90b2-8cd40060ed0e.gif)

The drag-and-drop system is not as smooth as in Windows, and the floating buttons don't appear. I don't know if this issue depends on the desktop enviroment.

**Comment by KestrelAdrian** [comment]
> Several things to report:
> To compile the project on Ubuntu I had to edit those lines on `simple.pro`:
> 
> ```
> CONFIG(debug, debug|release) {
>     LIBS += -L$$OUT_PWD/../../src/ -lDockingPanes
> } else {
>     LIBS += -L$$OUT_PWD/../../src/release/ -lDockingPanes
> }
> ```
> 
> On another hand, I can confirm that the behavior is really strange, compare to Windows version (on which I made the last commits that I pushed recently). Here a gif:
> ![output](https://user-images.githubusercontent.com/17966040/86523758-86b22a00-be47-11ea-90b2-8cd40060ed0e.gif)
> 
> The drag-and-drop system is not as smooth as in Windows, and the floating buttons don't appear. I don't know if this issue depends on the desktop enviroment.

Ok, thanks for that.  I will take a look into it, there must just be changes in mouse tracking between Mac and linux.  It shouldn't be hard to fix.

Did you see any issues with the drop shadow?

**Comment by lmsoria** [comment]
> > Several things to report:
> > To compile the project on Ubuntu I had to edit those lines on `simple.pro`:
> > ```
> > CONFIG(debug, debug|release) {
> >     LIBS += -L$$OUT_PWD/../../src/ -lDockingPanes
> > } else {
> >     LIBS += -L$$OUT_PWD/../../src/release/ -lDockingPanes
> > }
> > ```
> > 
> > 
> > On another hand, I can confirm that the behavior is really strange, compare to Windows version (on which I made the last commits that I pushed recently). Here a gif:
> > ![output](https://user-images.githubusercontent.com/17966040/86523758-86b22a00-be47-11ea-90b2-8cd40060ed0e.gif)
> > The drag-and-drop system is not as smooth as in Windows, and the floating buttons don't appear. I don't know if this issue depends on the desktop enviroment.
> 
> Ok, thanks for that. I will take a look into it, there must just be changes in mouse tracking between Mac and linux. It shouldn't be hard to fix.
> 
> Did you see any issues with the drop shadow?

Ups, sorry, I haven't mentioned it. No, at least in my setup I cannot see the shadows issue.

**Comment by KestrelAdrian** [comment]
I'll spin up an ubuntu VM and see what is going on, it seems to be a similar behaviour to what I've experienced on macOS.

It actually looks quite good under Linux!  Anything you'd like or would prefer to look different?

Maybe creating a style class to allow different visual styles to be used, I don't think it could be done with stylesheets as there's too much customisation that needs to be done.

As I've said this is a old project (although still being used in our full product!) that we decided to open source to the community so giving it a fresher look might be nice!

**Comment by lmsoria** [comment]
I quite like how the UI looks! It's okay for me leaving it as it is. The stylesheets support looks like a good feature for a future, though. Please let me know if you can replicate the issue! I will continue doing some cleanup to the rest of classes (one PR per class, to keep things clear)

**Comment by lmsoria** [comment]
Hi Adrian, I hope you are fine. I'm glad to inform you that I have found a fix for this issue (among other things). The example is working like a charm on Ubuntu 16.04. Now I'm going to see if my fixes don't break Windows version.

The only thing is, I worked on the fix on a personal branch `lmsoria-dev`, which I have merged several sub branches with technical debts. Feel free to see how it looks on my account, and if you agree, I can create a PR against your repo so we have them synced!

**Comment by fizzyade** [comment]
> Hi Adrian, I hope you are fine. I'm glad to inform you that I have found a fix for this issue (among other things). The example is working like a charm on Ubuntu 16.04. Now I'm going to see if my fixes don't break Windows version.
> 
> 
> 
> The only thing is, I worked on the fix on a personal branch `lmsoria-dev`, which I have merged several sub branches with technical debts. Feel free to see how it looks on my account, and if you agree, I can create a PR against your repo so we have them synced! 

Hi. Thanks for your work, I will take a look tomorrow and feel free to submit PR's and I will integrate them into the main repo.

Sadly my father passed away recently and this has impacted on our work schedule, so we are very busy on our commercial activities at the moment so I haven't had a chance to get back to this.

I will however happily look and a merge in any code changes in my spare time (I have insomnia so am often awake till just before the day starts).  On my list of things to do, are to comments throughout the code just to make clear how things work (or should work).

If you have any suggestions, ideas, questions and so forth then please contact me!

Can I ask what you are or will be using the library for? As you are providing patches and work I'd be happy to provide you with a license that didn't have the GPL terms attached to it as recompense for your work & efforts :)

As I've mentioned before, I wrote the library many years ago (Qt 4) and since then it's been the core of the GUI of our software product (which you are obviously aware is only windows!) so it's used a lot and seems to behave for the most part, as you'd expect.  

I'm sure there are bugs and enhancements that could be made, but as it is, it serves us well and I've not had to look at the code properly in a long time.

I'll pull your fork in the morning and compile on Ubuntu and take a look!

Once again, thank you for your time and effort.

**Comment by lmsoria** [comment]
Hi Adrian, 
I'm so sorry to hear that. It's a pretty though situation. I hope you get better soon.

On the next days I will create several PRs, one for each class. I've solved just minor issues (tech debts) so they shouldn't be hard to review. Once all of those PR get merged, your `master` branch should be equal to my `lmsoria-dev` branch, and then I can create the PR with the fix. 

The only class I haven't touched yet (I'm currently doing it, just a little bit) is `DockingPaneManager`. I may address you some questions on these upcoming days.

Thanks for your license offering! I'm maintaining a desktop application that basically connects to robots via TCP/IP and monitors the information generated by them (sensor readings, basically). Then process this data and plot graphs, log it on files, among other things. It's an internal tool (we don't distribute it) so we are OK with GPL license. However, if I have another project I will ask you for a license in case I need it :) Thanks!

**Comment by KestrelAdrian** [comment]
fixed by @lmsoria, closing issue.
